// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QUItkDWojDwUOg-pM02lKu4aKD0g12Q',
    appId: '1:1017667721793:web:c30e51698f85a2052584c0',
    messagingSenderId: '1017667721793',
    projectId: 'scansenti',
    authDomain: 'scansenti.firebaseapp.com',
    storageBucket: 'scansenti.firebasestorage.app',
    measurementId: 'G-J7K37L1SN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ht4lzqTa2U4HdN7_kKa93j_2WJ1sz1I',
    appId: '1:1017667721793:android:4e1475a23fd86ff52584c0',
    messagingSenderId: '1017667721793',
    projectId: 'scansenti',
    storageBucket: 'scansenti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_lnlxp_QYVo1kWC9AAiOmhTBM6IaJC3o',
    appId: '1:1017667721793:ios:84ac43d02673dbae2584c0',
    messagingSenderId: '1017667721793',
    projectId: 'scansenti',
    storageBucket: 'scansenti.firebasestorage.app',
    iosBundleId: 'com.example.scanSanti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_lnlxp_QYVo1kWC9AAiOmhTBM6IaJC3o',
    appId: '1:1017667721793:ios:84ac43d02673dbae2584c0',
    messagingSenderId: '1017667721793',
    projectId: 'scansenti',
    storageBucket: 'scansenti.firebasestorage.app',
    iosBundleId: 'com.example.scanSanti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_QUItkDWojDwUOg-pM02lKu4aKD0g12Q',
    appId: '1:1017667721793:web:93473e45e2cce0cd2584c0',
    messagingSenderId: '1017667721793',
    projectId: 'scansenti',
    authDomain: 'scansenti.firebaseapp.com',
    storageBucket: 'scansenti.firebasestorage.app',
    measurementId: 'G-Y3J965C5Q2',
  );
}
